[tool.poetry]
name = "squonk2-desc-rdkit"
version = "0.1.0"
description = "Calculate RDkit descriptors and fingerprints"
authors = [
  "Tim Dudgeon <tdudgeon@informaticsmatters.com>",
  "Kalev Takkis <ktakkis@informaticsmatters.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13.7"
im-data-manager-job-utilities = ">=1.4.0"
im-standardize-molecule = ">=0.1.0"
# The caret that used to be here (rdkit = "^2025.9.1") was not the problem it
# looked like. RDKit uses CalVer, so '^2025.9.1' means '>=2025.9.1,<2026.0.0'
# and does block 2026.x - but the reason a newer RDKit could not be found was
# im-rdkit-utilities 1.1.2, which pinned 'rdkit == 2025.9.1' exactly. 1.2.0
# relaxes that to '>=2026.3.6'.
rdkit = ">=2026.3.6"
im-rdkit-utilities = ">=1.2.0"


[tool.poetry.group.dev.dependencies]
im-jote = ">=0.14.0"
pre-commit = "^3"
pylint = "^3"
isort = "^5.13.2"
black = "^24.8.0"
mypy = "^1.11.1"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
